### ISSUE TITLE
Many tests failing with `TypeError: Unsupported type as file input: <class '_io.BytesIO'>`

### ISSUE THREAD

**Issue by jams2** [wagtail/Willow#100]
Appears to have been introduced in https://github.com/wagtail/Willow/commit/084a112aac21af97d0924c9447c739722cd4539e, which replaced `imghdr` with `filetype`. `filetype` does not handle `BytesIO` as input.

Opening this to track the issue, I've also opened https://github.com/h2non/filetype.py/issues/140 and will submit a patch if `filetype` maintainers are into it.

**Comment by gasman** [comment]
Fixed in #101
