### ISSUE TITLE
AVIF support

### ISSUE THREAD

**Issue by jorenham** [wagtail/Willow#111]
In the 1.5 release, `pillow-heif` has been used to add .heic support. I noticed that `pillow-heif` also has .avif functionality. And as far as I can tell, .heic will probably not win the browser-adaptation game against avif, due to its licensing. 
So I think I'd be a good addition to integrate avif, as well. It should be an easy to add to willow, at the very least.

**Comment by thibaudcolas** [comment]
Hi @jorenham, thanks for raising this. I’ve been following https://github.com/python-pillow/Pillow/pull/5201 for a while hoping to see AVIF support directly in Pillow, and didn’t realise `pillow-heif` was another option!

Just comparing what codecs are used:

- `pillow-heif` uses [`libheif`](https://github.com/strukturag/libheif), which has libaom, dav1d, SVT-AV1, rav1e
- `pillow-avif-plugin` / the Pillow PR use [`libavif`](https://github.com/AOMediaCodec/libavif), which has libaom, dav1d, SVT-AV1, rav1e, and libgav1

**Comment by thibaudcolas** [comment]
I’ve opened [AVIF support in Wagtail](https://github.com/wagtail/wagtail/issues/10486) as a separate issue. Support in Willow is the first step, but I believe tracking this on Wagtail’s bug tracker too will give this more visibility.
