### ISSUE TITLE
SvgViewBoxParseError at /cms/images/

### ISSUE THREAD

**Issue by bachi76** [wagtail/Willow#127]
### Issue Summary

Wagtail images breaks completely when it cannot parse an svg image correctly. Example given.
Error:
`SvgViewBoxParseError at /cms/images/
Unable to parse viewBox value '-5.000000011410315e-06 0.0 750.00001 525.000007'`

Notice the -5.000000011410315e-06 value which is likely the culprit. However, the svg validates as valid.

### Steps to Reproduce

Upload the attached svg image, then in Wagtail go to "Images". Or try to add one to a page using the chooser.

### Technical details

-   Python version: 3.11
-   Django version: 4.2
-   Wagtail version: 5.0
-   Browser version: irrelevant
![Home_hero](https://github.com/wagtail/wagtail/assets/1873207/590c86b0-1f33-478f-ad13-250d4e34c057)
![Auswahl_847](https://github.com/wagtail/wagtail/assets/1873207/4a76e154-0a7d-4961-b00b-b9c03e522a84)

**Comment by zerolab** [comment]
@bachi76 thank you for reporting this. I've moved it to the Willow issue queue as this is where the underlying issue is (https://github.com/wagtail/Willow/blob/main/willow/svg.py#L256) which is failing because of the https://github.com/wagtail/Willow/blob/main/willow/svg.py#L124-L128 regex

**Comment by bachi76** [comment]
Wow - that was fast - thanks @zerolab !

**Comment by zerolab** [comment]
All thanks to @jams2 👏🏼
