### ISSUE TITLE
OpenCV 3 Support

### ISSUE THREAD

**Issue by wgiddens** [wagtail/Willow#30]
Python 3 only works with OpenCV 3.  Are there plans to migrate the opencv backend to the new version?

**Comment by kaedroho** [comment]
Yep, there are plans for that. Just not got round to it yet!

Ideally, we would make the OpenCV backend work with both 2 and 3 so existing installations don't need to update it (OpenCV installation can be a bit tricky).

**Comment by kaedroho** [comment]
#33 now merged into master.

Thanks @wgiddens!
