### ISSUE TITLE
Willow 0.3.1 tarball has wrong version number

### ISSUE THREAD

**Issue by mans0954** [wagtail/Willow#43]
Running the commands:

```
wget https://github.com/torchbox/Willow/archive/v0.3.1.tar.gz
tar xf v0.3.1.tar.gz 
cat Willow-0.3.1/setup.py | grep version=
```

produces the output

`version='0.4a0'`

**Comment by kaedroho** [comment]
Oops, thanks for reporting!

**Comment by mans0954** [comment]
It's wrong in `Willow-0.3.1/willow/__init__.py` as well:

```
cat Willow-0.3.1/willow/__init__.py | grep __version__
__version__ = '0.4a0'

```

**Comment by zerolab** [comment]
Now that version 0.4 is out, is this relevant?

On a side note, @kaedroho there is no `stable/0.4.x` branch

**Comment by mans0954** [comment]
@zerolab Probably not!

**Comment by kaedroho** [comment]
There's not a lot we can do about this now, so closing
