### ISSUE TITLE
upload fails for animated gif using willow with wagtail

### ISSUE THREAD

**Issue by nuljon** [wagtail/Willow#68]
File "C:\Users\Student\Envs\CMS\lib\site-packages\willow\plugins\opencv.py", line 61, in from_buffer_rgb
    image = image.reshape(image_buffer.size[1], image_buffer.size[0], 3)
ValueError: cannot reshape array of size 8952300 into shape (343,435,3)

I get this error on three different gif images while uploading in wagtail 2.2.2. two images I created and one random from the internet. I am not sure but it looks like trying to make an rgb array of 3 channels?

**Comment by nuljon** [comment]
wrong issue tracker

**Comment by kaedroho** [comment]
Thanks! Please could you post on Wagtail's image tracker? It looks like we should be checking whether the image is animated at this point https://github.com/wagtail/wagtail/blob/882f8f3cf8ddd79c30e611a48882b309e90dad0c/wagtail/images/signal_handlers.py#L14-L18

Should be an easy fix.
