### ISSUE TITLE
Many tests are currently failing.

### ISSUE THREAD

**Issue by stefanistrate** [wagtail/Willow#84]
While testing in the following environment:

mock==1.0.1
numpy==1.18.1
opencv-python==4.1.2.30
Pillow==7.0.0
Wand==0.5.8

I noticed many tests were failing.

1. `test_wand.py` has two references to `PillowImage` instead of `WandImage`.

```
ERROR: test_open_webp (tests.test_wand.TestWandOperations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/istefan/workspace/Willow/tests/test_wand.py", line 195, in test_open_webp
    image = PillowImage.open(WebPImageFile(f))
NameError: name 'PillowImage' is not defined
```

2. `test_detect_faces` in `test_opencv.py` is failing because OpenCV computes slightly different values. To me this proves that the test is not that well designed in the first place. Should this be dropped?

```
FAIL: test_detect_faces (tests.test_opencv.TestOpenCVOperations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/istefan/workspace/Willow/tests/test_opencv.py", line 57, in test_detect_faces
    self.assertEqual(faces, self.expected_faces)
AssertionError: Lists differ: [(272, 88, 365, 181), (90, 164, 188, 262)] != [(272, 89, 364, 181), (91, 165, 187, 261)]

First differing element 0:
(272, 88, 365, 181)
(272, 89, 364, 181)

- [(272, 88, 365, 181), (90, 164, 188, 262)]
?         ^    ^          ^    ^    ^    ^

+ [(272, 89, 364, 181), (91, 165, 187, 261)]
?         ^    ^          ^    ^    ^    ^
```

3. One assertion in `test_jpeg_with_orientation_5` (`test_wand.py`) fails due to a bigger delta.

```
FAIL: test_jpeg_with_orientation_5 (tests.test_wand.TestWandImageOrientation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/istefan/workspace/Willow/tests/test_wand.py", line 266, in test_jpeg_with_orientation_5
    self.assert_orientation_landscape_image_is_correct(image)
  File "/Users/istefan/workspace/Willow/tests/test_wand.py", line 218, in assert_orientation_landscape_image_is_correct
    self.assertAlmostEqual(colour.red * 255, 217, delta=12)
AssertionError: 204.0 != 217 within 12 delta (13.0 difference)
```

4. `test_set_background_color_rgb` (`test_wand.py`) fails on the assertion below. It's a mystery to me why this happens.

```
FAIL: test_set_background_color_rgb (tests.test_wand.TestWandOperations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/istefan/workspace/Willow/tests/test_wand.py", line 60, in test_set_background_color_rgb
    self.assertFalse(red_background_image.has_alpha())
AssertionError: True is not false
```

**Comment by gasman** [comment]
> test_wand.py has two references to PillowImage instead of WandImage

Was fixed in 70e7c343e6111e81c020fff67afb5b787619376d.

> test_detect_faces in test_opencv.py is failing because OpenCV computes slightly different values. To me this proves that the test is not that well designed in the first place. Should this be dropped?

Haven't set up OpenCV yet, but this can surely be fixed by setting a suitable threshold on the result.

> One assertion in test_jpeg_with_orientation_5 (test_wand.py) fails due to a bigger delta.
>
> test_set_background_color_rgb (test_wand.py) fails on the assertion below. It's a mystery to me why this happens.

These pass on Imagemagick 6, but fail on version 7. In the case of `test_set_background_color_rgb`, it looks like this line

https://github.com/wagtail/Willow/blob/31fe99cd4f5988aa4366629f7fcc6f2029b474da/willow/plugins/wand.py#L119-L120

which was needed as a workaround on Imagemagick 6 for `clone.image.alpha_channel = 'remove'` failing to set the flag to False, now trips up Imagemagick 7 (presumably because `False` is [not a legal value to set](https://docs.wand-py.org/en/0.6.7/wand/image.html#wand.image.BaseImage.alpha_channel)), so it perversely responds by setting it back to True...
