### ISSUE TITLE
Support for HEIC/heif images

### ISSUE THREAD

**Issue by hpoul** [wagtail/Willow#90]
Any plans on supporting heic images?
I guess the first problem will be that `imghdr` does not support heif images, and it [doesn't look like there are any plans on supporting it](https://bugs.python.org/issue38170).

My workaround right now is to use [pyheif-pillow-opener](https://github.com/ciotto/pyheif-pillow-opener) to convert the images to jpg during upload. Are there any better options? 🤔️

**Comment by bigcat88** [comment]
maybe a `pillow-heif` will be better.  i'm pretty sure it will be. =)

**Comment by bigcat88** [comment]
@hpoul do you still need this?
I can made a PR to allow accepting HEIF files to Pillow, OpenCV and probably Wand too.

**Comment by gasman** [comment]
Implemented in #105
